import Head from 'next/head'
import Image from 'next/image'
import Highlights from '../src/components/Highlights'
import Menu from '../src/components/Menu'
import Sobre from '../src/components/Sobre'
import Homenagens from '../src/components/Homenagem';

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Homenagem a Marília Mendonça</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Highlights />

      <Sobre />
      <Homenagens />



      <footer className={styles.footer}>
        <p

        >
          Esta plataforma é uma homenagem a Marília Mendonça
        </p>
      </footer>
    </div >
  )
}
